const customTableStyles = {
    table: {
        style: {
            backgroundColor: '#fff',
            borderRadius: '0px',
            width: '100%',
            minWidth: '900px',
            maxWidth: '100%',
            tableLayout: 'auto',
            borderCollapse: 'separate',
            borderSpacing: 0,
            margin: 0,
        },
    },
    tableWrapper: {
        style: {
            overflowX: 'auto',
            overflowY: 'visible',
            width: '100%',
            maxWidth: '100%',
            border: 'none',
            borderRadius: '0',
            WebkitOverflowScrolling: 'touch',
            position: 'relative',
            scrollBehavior: 'smooth',
            scrollbarWidth: 'thin',
            scrollbarColor: '#10b981 #d1fae5',
            isolation: 'isolate',
        },
    },
    header: {
        style: {
            backgroundColor: '#f0fdf4',
            borderBottom: '2px solid #d1fae5',
            padding: '1rem 1.5rem',
            fontSize: '1.25rem',
            fontWeight: '600',
            textAlign: 'center',
        },
    },
    headRow: {
        style: {
            position: 'sticky',
            top: 0,
            zIndex: 1200,
            backgroundColor: '#f0fdf4',
            borderBottom: '2px solid #d1fae5',
            minHeight: '52px',
            boxShadow: '0 2px 4px rgba(16, 185, 129, 0.1)',
        },
    },
    headCells: {
        style: {
            paddingTop: '12px',
            paddingBottom: '12px',
            paddingLeft: '16px',
            paddingRight: '16px',
            fontWeight: '600',
            color: '#065f46',
            fontSize: '13px',
            textTransform: 'uppercase',
            letterSpacing: '0.025em',
            borderRight: '1px solid #d1fae5',
            whiteSpace: 'nowrap',
            overflow: 'visible',
            background: 'transparent',
            '&:last-child': {
                borderRight: 'none',
            },
            '&:first-child': {
                position: 'sticky',
                left: 0,
                zIndex: 1202,
                backgroundColor: '#f0fdf4',
                borderRight: 'none',
                boxShadow: 'none',
                paddingLeft: '8px',
                paddingRight: '4px',
            },
            '&:nth-child(2)': {
                position: 'sticky',
                left: '50px',
                zIndex: 1201,
                backgroundColor: '#f0fdf4',
                borderRight: '2px solid #d1fae5',
                boxShadow: '2px 0 4px rgba(16, 185, 129, 0.1)',
                paddingLeft: '4px',
                paddingRight: '8px',
            },
        },
    },
    cells: {
        style: {
            paddingTop: '12px',
            paddingBottom: '12px',
            paddingLeft: '16px',
            paddingRight: '16px',
            fontSize: '13px',
            color: '#475569',
            borderRight: '1px solid #f0fdf4',
            whiteSpace: 'normal',
            wordWrap: 'break-word',
            wordBreak: 'break-words',
            overflowWrap: 'break-word',
            minHeight: 'auto',
            height: 'auto',
            '&:last-child': {
                borderRight: 'none',
            },
            '&:first-child': {
                position: 'sticky',
                left: 0,
                zIndex: 999,
                backgroundColor: '#ffffff !important',
                borderRight: 'none',
                boxShadow: 'none',
                fontWeight: '600',
                color: '#475569',
                paddingLeft: '8px',
                paddingRight: '4px',
            },
            '&:nth-child(2)': {
                position: 'sticky',
                left: '50px',
                zIndex: 998,
                backgroundColor: '#ffffff !important',
                borderRight: '2px solid #d1fae5',
                boxShadow: '2px 0 4px rgba(16, 185, 129, 0.1)',
                paddingLeft: '4px',
                paddingRight: '8px',
            },
        },
    },
    rows: {
        style: {
            minHeight: '44px',
            height: 'auto',
            borderBottom: '1px solid #f0fdf4',
            transition: 'all 0.2s ease',
            '&:hover': {
                backgroundColor: '#f0fdf4',
                transform: 'translateY(-1px)',
                boxShadow: '0 2px 4px rgba(16, 185, 129, 0.1)',
            },
        },
        highlightOnHoverStyle: {
            backgroundColor: '#f0fdf4',
            transition: 'all 0.2s ease',
        },
    },
    pagination: {
        style: {
            borderTop: '1px solid #d1fae5',
            borderRadius: '0 0 12px 12px',
            padding: '12px 16px',
            backgroundColor: '#f0fdf4',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: '8px',
        },
    },
    noData: {
        style: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '400px',
            backgroundColor: '#ffffff',
            color: '#10b981',
            fontSize: '16px',
            fontWeight: '500',
            textAlign: 'center',
        },
    },
    progress: {
        style: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '400px',
            backgroundColor: '#ffffff',
        },
    },
};

// Named export for components that import using destructuring
export const enhancedTableStyles = customTableStyles;

export default customTableStyles;
