import React, { useState } from 'react';
import { act, fireEvent, render, screen, within } from '@testing-library/react';
import '@testing-library/jest-dom';
import { RowActionButton } from './PenjualanBoningPage';
import useBoningDocument from './hooks/useBoningDocument';
import service from '../../../../services/penjualanBoningService';
jest.mock('react-router-dom', () => ({}), { virtual: true });
jest.mock('./modals/AddEditBoningModal', () => () => null);
jest.mock('./modals/DetailBoningModal', () => () => null);
jest.mock('./modals/DeleteConfirmBoningModal', () => () => null);
jest.mock('../../../../services/penjualanBoningService', () => ({ __esModule: true, default: { downloadDocument: jest.fn() } }));
function Fixture() {
  const [open, setOpen] = useState(null);
  const docs = useBoningDocument();
  return <>{['one', 'two'].map(pid => <RowActionButton key={pid} row={{ pid, nama_pedagang: 'Same', no_kwitansi: '../SAME' }} isOpen={open === pid} onToggle={setOpen} onClose={() => setOpen(null)} {...docs} />)}{docs.downloadError && <p role="alert">{docs.downloadError}</p>}</>;
}
test('two same-label rows: PID loading, duplicate lock, portal focus, cleanup and errors', async () => {
  URL.createObjectURL = jest.fn(() => 'blob:fixture');
  URL.revokeObjectURL = jest.fn();
  const click = jest.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {});
  let resolve;
  service.downloadDocument.mockImplementation(() => new Promise(done => { resolve = done; }));
  render(<Fixture />);
  const triggers = screen.getAllByRole('button', { name: 'Menu aksi Same' });
  fireEvent.click(triggers[0]);
  let menu = screen.getByRole('menu');
  expect(within(menu).getByRole('menuitem', { name: 'Nota Penjualan PDF' })).toHaveFocus();
  for (const name of ['Detail', 'Edit', 'Hapus', 'Bayar']) expect(within(menu).getByRole('menuitem', { name })).toBeInTheDocument();
  fireEvent.click(within(menu).getByRole('menuitem', { name: 'Nota Penjualan PDF' }));
  expect(service.downloadDocument).toHaveBeenCalledWith('nota', { pid: 'one' });
  expect(screen.getByRole('menuitem', { name: 'Mengunduh...' })).toHaveAttribute('aria-busy', 'true');
  fireEvent.keyDown(menu, { key: 'Escape' });
  expect(triggers[0]).toHaveFocus();
  fireEvent.click(triggers[1]);
  menu = screen.getByRole('menu');
  const second = within(menu).getByRole('menuitem', { name: 'Nota Penjualan PDF' });
  expect(second).toBeDisabled();
  expect(second).toHaveAttribute('aria-busy', 'false');
  fireEvent.click(second);
  expect(service.downloadDocument).toHaveBeenCalledTimes(1);
  jest.useFakeTimers();
  await act(async () => resolve(new Blob(['%PDF-'])));
  expect(click.mock.instances[0].download).toBe('Nota_Boning____SAME.pdf');
  act(() => jest.advanceTimersByTime(1000));
  expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:fixture');
  jest.useRealTimers();
  service.downloadDocument.mockRejectedValue(new Error('Rekonsiliasi penjualan'));
  fireEvent.click(within(menu).getByRole('menuitem', { name: 'Surat Jalan PDF' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Rekonsiliasi');
  expect(service.downloadDocument).toHaveBeenLastCalledWith('surat-jalan', { pid: 'two' });
  click.mockRestore();
});
