export const pageTitleMap = {
  '/login': 'Secure Login',
  '/dashboard': 'Dashboard Aman',
  '/sales': 'Penjualan',
  '/purchases': 'Pembelian',
  '/delivery-orders': 'Surat Jalan',
  '/inventory/livestock': 'Stok Ternak',
  '/inventory/meat': 'Stok Daging',
  '/master-data/kandang-office': 'Data Master: Kandang & Office',
  '/master-data/jenis-hewan': 'Data Master: Jenis Hewan',
  '/master-data/klasifikasi-hewan': 'Data Master: Klasifikasi Hewan',
  '/master-data/klasifikasi-ovk': 'Data Master: Klasifikasi OVK',
  '/master-data/klasifikasi-feedmil': 'Data Master: Klasifikasi Feedmil',
  '/master-data/item-kulit': 'Data Master: Item Kulit',
  '/master-data/supplier': 'Data Master: Supplier',
  '/master-data/pelanggan': 'Data Master: Pelanggan',
  '/master-data/outlet': 'Data Master: Outlet',
  '/master-data/produk-gds': 'Data Master: Produk Gudang',
  '/master-data/eartag': 'Data Master: Eartag',
  '/ho/pembelian': 'Pembelian Doka & Sapi',
  '/ho/pembelian/add': 'Tambah Pembelian Doka & Sapi',
  '/ho/pembelian/edit/:id': 'Edit Pembelian Doka & Sapi',
  '/ho/pembelian/detail/:id': 'Detail Pembelian Doka & Sapi',
  '/ho/distribusi/:id': 'Head Office: Distribusi Ternak',
  '/ho/penjualan': 'Head Office: Penjualan',
  '/ho/penjualan/add': 'Head Office: Tambah Penjualan',
  '/ho/penjualan/edit/:id': 'Head Office: Edit Penjualan',
  '/ho/penjualan/detail/:id': 'Head Office: Detail Penjualan',
  '/boning/keuangan': 'Boning: Keuangan',
  '/boning/pembelian': 'Boning: Pembelian',
  '/boning/penjualan': 'Boning: Penjualan',
  '/boning/stok-daging': 'Boning: Stok Daging',
  '/boning/return': 'Boning: Return',
  '/boning/surat-jalan': 'Boning: Surat Jalan',
  '/system/roles': 'System: Role Management',
  '/system/permission-management': 'System: Permission Management',
  '/system/users': 'System: User Management',
  '/system/parameters': 'System: Parameter Management',
  '/reports': 'Laporan',
  '/reports/nota-supplier': 'Laporan: Nota Supplier',
  '/reports/semua-supplier': 'Laporan: Semua Supplier',
  '/reports/pajak': 'Laporan: Pajak',
  '/hr/employees': 'Data Karyawan',
  '/hr/attendance': 'Absensi',
  '/hr/leave-requests': 'Pengajuan Cuti',
  '/settings': 'Pengaturan Keamanan',
  '/ho/pembelian-feedmil': 'Head Office: Pembelian Feedmil',
  '/ho/pembelian-feedmil/add': 'Head Office: Tambah Pembelian Feedmil',
  '/ho/pembelian-feedmil/edit/:id': 'Head Office: Edit Pembelian Feedmil',
  '/ho/pembelian-feedmil/detail/:id': 'Head Office: Detail Pembelian Feedmil',
  '/ho/pembelian-ovk': 'Head Office: Pembelian OVK',
  '/ho/pembelian-ovk/add': 'Head Office: Tambah Pembelian OVK',
  '/ho/pembelian-ovk/edit/:id': 'Head Office: Edit Pembelian OVK',
  '/ho/pembelian-ovk/detail/:id': 'Head Office: Detail Pembelian OVK',
};
