import React from 'react';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import BeriMakanSapiPage from './BeriMakanSapiPage';
import Pakan from '../../../../services/persediaanPakanService';
import Sapi from '../../../../services/stokSapiService';
import { configureInventoryScope, resetInventoryScope, setInventoryPage } from '../../../../services/inventoryScope';

jest.mock('react-router-dom', () => ({ useNavigate: () => jest.fn(), useParams: () => ({}) }), { virtual: true });
jest.mock('react-data-table-component', () => ({ data }) => <div>{data.map(row => <span key={row.pid}>{row.eartag}</span>)}</div>);
jest.mock('../../../../services/persediaanPakanService', () => ({ getResepData: jest.fn(), showResep: jest.fn(), beriMakan: jest.fn() }));
jest.mock('../../../../services/stokSapiService', () => ({ getStokSapiOptions: jest.fn() }));
jest.mock('../../../../services/kandangService', () => ({}));
beforeEach(() => {
  jest.clearAllMocks();
  resetInventoryScope();
  localStorage.setItem('user', JSON.stringify({ id_office: 7, module_scope: 'rph' }));
  Pakan.getResepData.mockImplementation(async ({ id_rph }) => ({ success: true, data: [{ pid: `feed-${id_rph}`, name: `Feed ${id_rph}` }] }));
  Pakan.showResep.mockImplementation(async pid => ({ success: true, data: { pid, name: pid, tgl_aktif: '2026-09-28' } }));
  Sapi.getStokSapiOptions.mockResolvedValue({ success: true, data: { rows: [] } });
});
afterEach(resetInventoryScope);
test('ALL requires concrete office; transition clears feed/cattle and ignores late responses', async () => {
  configureInventoryScope({ id: 1, inventory_scope: 'all_rph' }, [{ id: 7, name: 'A' }, { id: 8, name: 'B' }]);
  setInventoryPage('/rph/persediaan-ovk');
  let completeOld;
  Sapi.getStokSapiOptions.mockImplementationOnce(() => new Promise(resolve => { completeOld = resolve; }));
  render(<BeriMakanSapiPage initialItem={{ pid: 'old' }} onClose={jest.fn()} />);
  expect(screen.getByLabelText('RPH Pemberian Pakan')).toHaveValue('');
  expect(Pakan.showResep).not.toHaveBeenCalled();
  expect(screen.getByRole('button', { name: 'Beri Makan' })).toBeDisabled();
  fireEvent.change(screen.getByLabelText('RPH Pemberian Pakan'), { target: { value: '7' } });
  await screen.findByRole('option', { name: 'Feed 7' });
  fireEvent.change(screen.getByLabelText('Resep Pakan'), { target: { value: 'feed-7' } });
  await waitFor(() => expect(Sapi.getStokSapiOptions).toHaveBeenCalledWith('2026-09-28', '7'));
  fireEvent.change(screen.getByLabelText('RPH Pemberian Pakan'), { target: { value: '8' } });
  expect(screen.getByLabelText('Resep Pakan')).toHaveValue('');
  expect(screen.getByRole('button', { name: 'Beri Makan' })).toBeDisabled();
  await act(async () => completeOld({ success: true, data: { rows: [{ pid: 'old-cow', eartag: 'STALE COW' }] } }));
  expect(screen.queryByText('STALE COW')).not.toBeInTheDocument();
  await screen.findByRole('option', { name: 'Feed 8' });
  expect(screen.queryByRole('option', { name: 'Feed 7' })).not.toBeInTheDocument();
});
test('ordinary RPH modal locks assigned office', async () => {
  render(<BeriMakanSapiPage initialItem={{ pid: 'old' }} onClose={jest.fn()} />);
  expect(screen.getByLabelText('RPH Pemberian Pakan')).toHaveAttribute('readonly');
  expect(screen.getByLabelText('RPH Pemberian Pakan')).toHaveValue('RPH 7');
  await screen.findByRole('option', { name: 'Feed 7' });
});
test('office transition drops late recipe detail and selected cattle; submission uses modal office', async () => {
  configureInventoryScope({ id: 1, inventory_scope: 'all_rph' }, [{ id: 7, name: 'A' }, { id: 8, name: 'B' }]);
  setInventoryPage('/rph/persediaan-ovk');
  let completeDetail;
  Pakan.showResep.mockImplementationOnce(() => new Promise(resolve => { completeDetail = resolve; }));
  Sapi.getStokSapiOptions.mockResolvedValue({ success: true, data: { rows: [{ pid: 'cow-b', eartag: 'Cow B' }] } });
  Pakan.beriMakan.mockResolvedValue({ success: true });
  render(<BeriMakanSapiPage initialItem={{ pid: 'old' }} onClose={jest.fn()} onSuccess={jest.fn()} />);
  fireEvent.change(screen.getByLabelText('RPH Pemberian Pakan'), { target: { value: '7' } });
  await screen.findByRole('option', { name: 'Feed 7' });
  fireEvent.change(screen.getByLabelText('Resep Pakan'), { target: { value: 'feed-7' } });
  await waitFor(() => expect(Pakan.showResep).toHaveBeenCalledWith('feed-7', '7'));
  fireEvent.change(screen.getByLabelText('RPH Pemberian Pakan'), { target: { value: '8' } });
  await act(async () => completeDetail({ success: true, data: { pid: 'old', name: 'STALE FEED', tgl_aktif: '2026-09-28' } }));
  expect(screen.queryByText('STALE FEED')).not.toBeInTheDocument();
  expect(Sapi.getStokSapiOptions).not.toHaveBeenCalled();
  await screen.findByRole('option', { name: 'Feed 8' });
  fireEvent.change(screen.getByLabelText('Resep Pakan'), { target: { value: 'feed-8' } });
  await screen.findByText('Cow B');
  fireEvent.change(screen.getByLabelText('Nama Peternak (opsional)'), { target: { value: 'Budi' } });
  const calls = [Pakan.getResepData.mock.calls.length, Pakan.showResep.mock.calls.length, Sapi.getStokSapiOptions.mock.calls.length];
  fireEvent.blur(window);
  fireEvent(document, new Event('visibilitychange'));
  fireEvent.focus(window);
  expect(screen.getByLabelText('Nama Peternak (opsional)')).toHaveValue('Budi');
  expect(screen.getByLabelText('RPH Pemberian Pakan')).toHaveValue('8');
  expect(screen.getByLabelText('Resep Pakan')).toHaveValue('feed-8');
  expect([Pakan.getResepData.mock.calls.length, Pakan.showResep.mock.calls.length, Sapi.getStokSapiOptions.mock.calls.length]).toEqual(calls);
  fireEvent.click(screen.getByRole('button', { name: 'Beri Makan' }));
  await waitFor(() => expect(Pakan.beriMakan).toHaveBeenCalledWith(expect.objectContaining({ id_rph: 8, pid: 'feed-8', selected_sapi_pids: ['cow-b'] })));
  fireEvent.change(screen.getByLabelText('RPH Pemberian Pakan'), { target: { value: '7' } });
  expect(screen.queryByText('Cow B')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Beri Makan' })).toBeDisabled();
  await screen.findByRole('option', { name: 'Feed 7' });
});
